config/routes.rb
Chesster::Application.routes.draw do

  resources :games
  devise_for :users
  get 'games/:id/:piece_id/:x_coord/:y_coord', :to => 'games#select', :as => 'select'
  post 'games/:id/:piece_id/:x_coord/:y_coord', :to => 'games#move', :as => 'move'

  root 'static_pages#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :pieces
	has_many :pawns
	has_many :rooks 
	has_many :queens
	has_many :kings
	has_many :knights
	has_many :bishops

	belongs_to :user
  belongs_to :opponent, :foreign_key => 'opponent_id', :class_name => User
	scope :for_user, lambda {|user_id| where("user_id = ? OR opponent_id = ?", user_id, user_id)}
	before_save :default_values
  
	INITIAL_BOARD_PIECES = [
		['white', [0, 0], 'rook'],
		['white', [1, 0], 'knight'],
		['white', [2, 0], 'bishop'],
		['white', [3, 0], 'queen'],
		['white', [4, 0], 'king'],
		['white', [5, 0], 'bishop'],
		['white', [6, 0], 'knight'],
		['white', [7, 0], 'rook'],
		['white', [0, 1], 'pawn'],
		['white', [1, 1], 'pawn'],
		['white', [2, 1], 'pawn'],
		['white', [3, 1], 'pawn'],
		['white', [4, 1], 'pawn'],
		['white', [5, 1], 'pawn'],
		['white', [6, 1], 'pawn'],
		['white', [7, 1], 'pawn'],
		['black', [0, 7], 'rook'],
		['black', [1, 7], 'knight'],
		['black', [2, 7], 'bishop'],
		['black', [3, 7], 'queen'],
		['black', [4, 7], 'king'],
		['black', [5, 7], 'bishop'],
		['black', [6, 7], 'knight'],
		['black', [7, 7], 'rook'],
		['black', [0, 6], 'pawn'],
		['black', [1, 6], 'pawn'],
		['black', [2, 6], 'pawn'],
		['black', [3, 6], 'pawn'],
		['black', [4, 6], 'pawn'],
		['black', [5, 6], 'pawn'],
		['black', [6, 6], 'pawn'],
		['black', [7, 6], 'pawn']
	]

	def initialize_the_board!
		INITIAL_BOARD_PIECES.each do |piece|
			# meta-code that generates a new piece based on each row of the INITIAL_BOARD_PIECES array
			# e.g. for last row, it results in
			#   self.pawns.create(:color => piece[0], :x_coord => piece[1][0], :y_coord => piece[1][1], :image => Pawn.get_image(piece[0]))
			self.send("#{piece[2]}s").create(:color => piece[0], :x_coord => piece[1][0], :y_coord => piece[1][1], :image => piece[2].titleize.constantize.get_image(piece[0]))
		end
	end

	def next_player
		if self.player_turn == "white"
			self.update_attributes(player_turn: "black")
			return true
		elsif self.player_turn == "black"
			self.update_attributes(player_turn: "white")
			return true
		else
			return nil
		end
	end

  def get_player_color(user_id)
    if user_id == self.user.id 
      return "white"
    elsif user_id == self.opponent.id
      return "black"
    else
      return nil
    end
  end

	def is_move_obstructed?(piece_id, new_x, new_y)
		# does the following operations:
		# - get all tile coordinates between current piece tile and destination tile (list A)
		# - gets coordinates of all pieces in game (list B)
		# - checks whether there is any overlap between list A and list B
		#      - if so, it returns 'true' (there is an obstruction)
		#  	   - if not, it returns 'false' (there is no obstruction)
		# - if destination tile is not on a horizontal / vertical / perfect diagonal relative
		#   to current piece tile, then 'nil' is returned (move isn't valid)
		current_piece = Piece.find(piece_id)

		# check that the destination is a horizontal/vertical/diagonal
		# line away from current piece
		x_diff = current_piece.x_coord - new_x
		y_diff = current_piece.y_coord - new_y

		if !(((x_diff == y_diff) || (x_diff == 0) || (y_diff == 0)))
		# Raise a BIG exception	
			return nil
		end

		# get list of coordinates of tiles between destionation tile
		# and current piece tile
		places_between = [ [new_x, new_y] ]
		back_to_start = false
		current_coordinates = [current_piece.x_coord, current_piece.y_coord]

		until back_to_start
			if new_x > current_piece.x_coord
				new_x = new_x - 1
			elsif new_x < current_piece.x_coord
				new_x = new_x + 1
			end

			if new_y > current_piece.y_coord
				new_y = new_y -  1
			elsif new_y < current_piece.y_coord
				new_y = new_y + 1
			end

			if current_coordinates == [new_x, new_y]
				back_to_start = true
			else
				if x_diff == y_diff
					places_between << [new_x, new_y]
				elsif x_diff == 0
					places_between << [current_piece.x_coord, new_y]
				else
					places_between << [new_x, current_piece.y_coord]
				end
			end
		end
		
		# get coordinates for all game pieces
		pieces = self.pieces.to_a
		#puts pieces.inspect
		all_piece_coordinates = pieces.map { |p| [p.x_coord, p.y_coord] }
		# check if any current game pieces overlap with 
		# the coordinates between target and current piece position
		obstruction = false
		all_piece_coordinates.each do |piece_coordinates|
			is_current_piece = current_coordinates == piece_coordinates
			is_destination_piece = piece_coordinates == [new_x, new_y]	

			if x_diff == 0 && y_diff == 0
				obstruction = true
			end

			if places_between.include?(piece_coordinates) && !is_current_piece && !is_destination_piece				
				obstruction = true
				break
			end		
		end
		return obstruction
	end

	private

		def default_values
		    self.player_turn ||= 'white'
		end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def new
    @game = Game.new
  end

  def create    
    new_opponent_id = game_params[:opponent_id]
    @game = Game.create(:opponent_id => new_opponent_id, :user_id => current_user.id)
    @game.initialize_the_board!
    @name =  @game.id.to_s
    # FIREBASE.push("/games/" + @game.id.to_s , { :game => @name, :time=>Time.now.to_i, :priority => 1 })
    redirect_to game_path(@game)
  end

  def show
  	@game = Game.find(params[:id])
  	@pieces = @game.pieces
  	#@player1 = User.find(@game.user_id)
  	#@player2 = User.find(@game.opponent_id)
    @player1 = @game.user
    @player2 = @game.opponent

    @current_user_color = @game.get_player_color(current_user.id)
    if @current_user_color == @game.player_turn
      @current_user_turn = true
    else
      @current_user_turn = false
    end 
  
  end


  def move
    @pieces = current_game.pieces
    @piece = Piece.find(params[:piece_id])
   
    FIREBASE.push("/games/",{:game=> current_game.id.to_s, :time=>Time.now.to_i, :x_coord=> @piece.x_coord, :y_coord=>@piece.y_coord})
    # FIREBASE.push("/games/",{:game=> current_game.id.to_s, :time=>Time.now.to_i, :pieces=>@pieces})
    # @piece = Piece.find(params[:piece_id])
    if ! @piece.move_piece!(params[:x_coord], params[:y_coord])
      flash[:notice] = "That was not a valid move"
    else
      @piece.game.next_player
    end
  # @game = Game.find(params[:id])  
  # :game=> @game,


   FIREBASE.push("/games/moves/",{:game=> current_game.id.to_s, :time=>Time.now.to_i, :image=>@piece.image, :piece_type=> @piece.type, :piece_id=> @piece.id, :x_coord=> @piece.x_coord, :y_coord=>@piece.y_coord, :color=>@piece.color})
   redirect_to game_path(@piece.game)
    # render "games/"+ @piece.game

  end

 
      
  private



  def current_game
    @current_game ||= Game.find(params[:id])
  end

	def game_params
		params.require(:game).permit(:opponent_id)
	end




end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Start a New Game</h1>
<p>You can start a new game by selecting another player who's registered on the Chesster server.</p>

<%= simple_form_for @game, :url => games_path do |f| %>
	<%= f.input :opponent_id, :collection => User.all %>
	<br/>
	<%= f.submit "Start Game", :class => 'btn btn-primary' %>
<% end %>

app/views/games/select.html.erb
<h1>Move your piece</h1>
<p>Click on the space that you want to move your piece to</p>
<div class="table-responsive">
	<table class="board table chess">
		<% first_tile_white = true %>
			<% 7.downto(0) do |row| %>
				<tr class="row row<%= row %>">
					<% 0.upto(7) do |column| %>	
						<td data-move-url="<%= move_path(@game,:piece_id => @piece.id, :x_coord => column,:y_coord => row) %>" class="col-xs-1 space <%= column %><%= row %> <%= tile_color(first_tile_white, column) %>">
						<% if @x_coord.to_i == column && @y_coord.to_i == row %>
							<%= image_tag(@piece.image, :class => "img-responsive selected") %>
						<% else %>
							<% @pieces.each do |piece| %>
							<% if piece.x_coord == column && piece.y_coord == row %>
								<%= image_tag(piece.image, :class=>"img-responsive") %>
							<% end%>
						<% end %>
					<% end %>
					</td>
				<% end %>
				</tr>
		<% first_tile_white = first_tile_white.! %>
		<% end %>
	</table>
</div>

<!-- csrf securty built into Rails throws  action controller error 'invalid authenticity token'
when using plain html form tag for this -->
	<%= form_tag "#", :id => 'move'%>

<script>
	$(function(){
			$('td').click(
				function(el){
					var path = $(el.target).closest('td').data("move-url");
					var $form =  $('#move');
					$form.attr('action', path); 
					console.log(path);
					$form.submit();
				});
	});
</script>

app/views/games/show.html.erb
<!-- 	<h1>Game#show</h1> -->
<%# if @current_user_turn %>

<div id='play' class="<%= @current_user_turn %>">		
	<h2>Click and drag the piece that you would like to move</h2>
		<p><b><%= @player1.email %></b> vs <b><%= @player2.email %></b></p>
		<div class="table-responsive">
		<table class="board table chess">

		<% first_tile_white = true %>
		<% 7.downto(0) do |row| %>
			<tr class="row row<%= row %>">
			<% 0.upto(7) do |column| %>		
				<td class="col-xs-1 space <%= column %><%= row %> <%= tile_color(first_tile_white, column) %>" id="<%= column %><%= row %>">
					<% @pieces.each do |piece| %>
					    <% if piece.x_coord == column && piece.y_coord == row && piece.color == @current_user_color %> 
					    	<%= link_to image_tag(piece.image, :class=>"img-responsive moveable " + piece.color, :id=>piece.id) %>
					    <% elsif piece.x_coord == column && piece.y_coord == row %>
					    	<%= image_tag(piece.image, :class=>"img-responsive", :id=>piece.id) %>
					    <% end%>
					<% end %>
				</td>
			<% end %>
			</tr>
			<% first_tile_white = first_tile_white.! %>
		<% end %>
		</table>
		</div>
</div>
	<%# else %>
<div id="wait" >		
	<h2>Waiting for other player to move...</h2>

		<p><b><%= @player1.email %></b> vs <b><%= @player2.email %></b></p>
		<div class="table-responsive">
		<table class="board table chess">

		<% first_tile_white = true %>
		<% 7.downto(0) do |row| %>
			<tr class="row row<%= row %>">
			<% 0.upto(7) do |column| %>		
				<td class="col-xs-1 space <%= column %><%= row %> <%= tile_color(first_tile_white, column) %>" id="<%= column %><%= row %>">
					<% @pieces.each do |piece| %>
					    <% if piece.x_coord == column && piece.y_coord == row %> 
					    	<%= image_tag(piece.image, :class=>"img-responsive " + piece.color, :id=>piece.id) %>
					    <% end%>
					<% end %>
				</td>
			<% end %>
			</tr>
			<% first_tile_white = first_tile_white.! %>
		<% end %>
		</table>
		</div>
	</div>
	<%#end %>

<%= form_tag "#", :id => 'move'%>


<script>
$(function() {
	var dragDrop = function(path){

    $(".moveable").draggable();
			$("td.space").droppable({
				drop: function( event, ui ) {
					var drop_target_id = event.target.id;
					var target_x = drop_target_id[0];
					var target_y = drop_target_id[1];
					var piece_id = ui.draggable.prop('id');
					var path = "/games/<%= @game.id.to_s %>/" + piece_id + "/" + target_x + "/" + target_y;
					var $form =  $('#move');
					$form.attr('action', path); 
					console.log(path);
					$form.submit();			
			      }		
				});
			};

		dragDrop();
//lines here


var playboard = $("div#play");
var wait = $("div#wait");

if ($("div").hasClass("true")) {
	playboard.show();
	wait.hide();
	} else if ($("div").hasClass("false")) {
	playboard.hide();
	wait.show();
	}

var message_play = "Click and drag the piece that you would like to move";
var message_wait = "Waiting for other player to move...";
var message_h = $("div > h2");

var origPieceLoc = new Firebase("https://burning-heat-9967.firebaseio.com/games/");
	var currentTime = <%= Time.now.to_i %>;

	origPieceLoc.on("child_added", function(snapshot) {
		var movedFrom = snapshot.val();
		if (movedFrom.time >= currentTime){
			orig_x = movedFrom.x_coord.toString();
			orig_y = movedFrom.y_coord.toString();
			var orig_spaceLoc = orig_x + orig_y;
			var orig_space = $("." + orig_spaceLoc);

			if ($("div").hasClass("false")){
				orig_space.html("");
			}



		

		}// end time if
	});//end of origPiece on child added


var movesRef = new Firebase("https://burning-heat-9967.firebaseio.com/games/moves");
	movesRef.on("child_added", function(snapshot) {
	var currentTime = <%= Time.now.to_i %>;
	var newMove = snapshot.val();

		if (newMove.time >= currentTime){

			var moved_piece = {
          game_id : newMove.game,
			 	 piece_id : newMove.piece_id,
					x_coord : newMove.x_coord,
					y_coord : newMove.y_coord,
					  image : newMove.image,
					  color : newMove.color
				 };

			moved_piece.x_coord = moved_piece.x_coord.toString();
			moved_piece.y_coord = moved_piece.y_coord.toString();
			var coords = moved_piece.x_coord + moved_piece.y_coord;
			var waitTwo = $("div#wait");
			var cell = waitTwo.find("td."+coords);
			cell.html("<img src=/assets/" + moved_piece.image + " class='img-responsive' />");//include 'hello' in html string to test that DOM is getting data from Firebase
			message_h.html(message_play);
			var color = "";
			moved_piece.color == "black"? color = "white" : color = "black";
			var pieces = waitTwo.find($("img."+ color));
			pieces.addClass("moveable");
			var pieceHref = "games/" + moved_piece.game_id;
		  pieces.wrap( "<a href='"+ pieceHref + "'></a>" );
		  



		  dragDrop();
			// window.location.href = "<%= url_for :controller => 'games', :action => 'show', :id => @game.id %>";

		};//currTime

	});//movesRef call back
});//parent
</script>