config/routes.rb
Chesster::Application.routes.draw do

  resources :games
  devise_for :users
  get 'games/:id/:piece_id/:x_coord/:y_coord', :to => 'games#select', :as => 'select'
  post 'games/:id/:piece_id/:x_coord/:y_coord', :to => 'games#move', :as => 'move'

  root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chesster</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
      <script src="https://cdn.firebase.com/js/client/2.1.1/firebase.js"></script>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
       <%= link_to root_path do %>

      <%= image_tag("chesster.png", :alt => "chesster", :class => 'img-responsive logo') %>
    
      <% end %>
    
   
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li><%= link_to 'Start New Game', new_game_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>      
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<% if alert.present? %>
<span class="alert"><%= alert %></span> 
<%end%>
	<% if notice.present? %>
<span class="notice"><%= notice %></span> 
<%end%>

<%= yield %>

</body>
</html>